import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

/**
 * Standalone tool — sinh BCrypt hash cho các tài khoản demo và in ra câu SQL UPDATE.
 *
 * Chạy:
 *   cd D:\PROJECTS_VANH\event-ticketing\backend
 *   .\hash-password.ps1
 */
public class HashPassword {

    public static void main(String[] args) {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(10);

        // Danh sách email → password cần hash
        String[][] accounts = {
            { "admin@event.local",     "Admin@123"   },
            { "organizer@event.local", "Organizer@123" },
            { "staff@event.local",     "Staff@123" },
            { "customer@event.local",  "Customer@123" },
        };

        System.out.println("-- ============================================================");
        System.out.println("-- SQL UPDATE password_hash cho database event_ticketing_dev");
        System.out.println("-- Generated by HashPassword.java");
        System.out.println("-- ============================================================");
        System.out.println();

        for (String[] account : accounts) {
            String email    = account[0];
            String password = account[1];
            String hash     = encoder.encode(password);

            System.out.printf(
                "UPDATE employees SET password_hash = '%s' WHERE email = '%s'; -- %s%n",
                hash, email, password
            );
        }
    }
}
